---
# This is the top-level playbook for deploying Koha
- hosts: all
  remote_user: vagrant
  gather_facts: true

  vars_files:
      - vars/defaults.yml
      - vars/user.yml

  pre_tasks:
    - name: Prevent installation of python-openssl on Debian Jessie
      copy:
        src: ./files/apt-koha.pref
        dest: /etc/apt/preferences.d/apt-koha.pref
        owner: root
        group: root
        mode: 0644
      become: yes
      when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'
    - name: Update apt cache if needed
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      become: yes

  roles:
      - kohadevbox

  post_tasks:
    - name: Init mlocate database
      shell: updatedb
      become: yes
